name: twilio metrics weekly

# Controls when the action will run.
on:
  # Triggers the workflow at 11AM PT
  schedule:
    - cron: '0 18 * * 1-5'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "actionItems"
  metrics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: make install

      - name: Run Metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_CREDS: ${{ secrets.GOOGLE_API_CREDS }}
        run: |
          echo "$(source venv/bin/activate && python examples/metrics.py --period weekly --include twilio-csharp twilio-java twilio-node twilio-php)"

      - name: Run Metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_CREDS: ${{ secrets.GOOGLE_API_CREDS }}
        run: |
          echo "$(source venv/bin/activate && python examples/metrics.py --period weekly --include twilio-python twilio-ruby twilio-cli twilio-cli-core)"

      - name: Run Metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_CREDS: ${{ secrets.GOOGLE_API_CREDS }}
        run: |
          echo "$(source venv/bin/activate && python examples/metrics.py --period weekly --include twilio-oai plugin-debugger homebrew-brew twilio-go)"

      - name: Run Metrics
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_CREDS: ${{ secrets.GOOGLE_API_CREDS }}
        run: |
          echo "$(source venv/bin/activate && python examples/metrics.py --period weekly --include twilio-oai-generator terraform-provider-twilio)"
